name: Tests

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  tests:
    name: ${{ matrix.python }} / ${{ matrix.os }} / dbt v${{ matrix.dbt }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Latest dbts' test matrix on 3.11 (well supported py version) on ubuntu
          - { python: "3.11", os: "ubuntu-latest", dbt: "1.4" }
          - { python: "3.11", os: "ubuntu-latest", dbt: "1.5" }
          - { python: "3.11", os: "ubuntu-latest", dbt: "1.6" }
          - { python: "3.11", os: "ubuntu-latest", dbt: "1.7" }
          - { python: "3.11", os: "ubuntu-latest", dbt: "1.8" }
          # full test matrix on 3.10 (well supported py version) on ubuntu
          - { python: "3.10", os: "ubuntu-latest", dbt: "1.0" }
          - { python: "3.10", os: "ubuntu-latest", dbt: "1.1" }
          - { python: "3.10", os: "ubuntu-latest", dbt: "1.2" }
          - { python: "3.10", os: "ubuntu-latest", dbt: "1.3" }
          - { python: "3.10", os: "ubuntu-latest", dbt: "1.4" }
          - { python: "3.10", os: "ubuntu-latest", dbt: "1.5" }
          - { python: "3.10", os: "ubuntu-latest", dbt: "1.6" }
          - { python: "3.10", os: "ubuntu-latest", dbt: "1.7" }
          - { python: "3.10", os: "ubuntu-latest", dbt: "1.8" }
          # full test matrix on 3.9 (well supported py version) on ubuntu
          - { python: "3.9", os: "ubuntu-latest", dbt: "1.0" }
          - { python: "3.9", os: "ubuntu-latest", dbt: "1.1" }
          - { python: "3.9", os: "ubuntu-latest", dbt: "1.2" }
          - { python: "3.9", os: "ubuntu-latest", dbt: "1.3" }
          - { python: "3.9", os: "ubuntu-latest", dbt: "1.4" }
          - { python: "3.9", os: "ubuntu-latest", dbt: "1.5" }
          - { python: "3.9", os: "ubuntu-latest", dbt: "1.6" }
          - { python: "3.9", os: "ubuntu-latest", dbt: "1.7" }
          - { python: "3.9", os: "ubuntu-latest", dbt: "1.8" }
          # stability test on 3.8 (min python ver) with latest dbt
          - { python: "3.8", os: "ubuntu-latest", dbt: "1.5" }
          # stability test on 3.10 with latest dbt on macos (cross platform)
          - { python: "3.10", os: "macos-latest", dbt: "1.5" }

    env:
      FORCE_COLOR: "1"
      PRE_COMMIT_COLOR: "always"

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}

      - name: Upgrade pip
        run: |
          pip install --constraint=.github/workflows/constraints.txt pip
          pip --version

      - name: Upgrade pip in virtual environments
        shell: python
        run: |
          import os
          import pip

          with open(os.environ["GITHUB_ENV"], mode="a") as io:
              print(f"VIRTUALENV_PIP={pip.__version__}", file=io)

      - name: Run Tests
        run: |
          make test-dbt${{ matrix.dbt }}

      # TODO: Upload docs
      # - name: Upload documentation
      #   if: matrix.session == 'docs-build'
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: docs
      #     path: docs/_build
